spring.application.name=main

spring.datasource.url=jdbc:postgresql://localhost:5432/nabavka_db
spring.datasource.username=postgres
spring.datasource.password=Lanadelrey789.

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

#disable spring security 
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration